### ISSUE TITLE
What are example use cases? 

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [tellnes/long-timeout#7]
Can we add some examples in the README of where this can be useful?

What are cases where you needed to setTimeout for longer than 28 days, and setTimeout was a more fitting solution than a scheduler that persists to a database?

**Comment by tellnes** [comment]
I don't remember the details as it is 8 years since I created this. By my use case back then was to set I timeout for when I needed to renew/reload some TLS certificates based on the expiration date. But looking at the dependents in the dependency graph you can can probably find a lot of more use cases. I guess more people than me have run into the same problem I did and found this useful since it currently is 24k repositories at GitHub that depends on this.
